server:
  port: 8080
  servlet:
    context-path: /open

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: test

# 日志配置
logging:
  level:
    com.open.platform: info
    org.springframework: warn

# MyBatis 映射
mybatis-plus:
  mapper-locations: classpath:mappers/**/*Mapper.xml
  type-aliases-package: com.open.platform.domain
  global-config:
    db-config:
      id-type: auto
      field-strategy: NOT_EMPTY
      db-type: MYSQL
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true

